name: chemtools
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12 # Assuming the user wants the latest Python as mentioned in the original request
  - plotly
  - flet
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - husl
  - polars
  - networkx
  - pyarrow